title: 시누의 블로그
subtitle: 코딩이랑 잡담이랑 뒤죽박죽
name: sinu
email: cpu344@gmail.com
description: >-
  코딩이랑 잡담이랑 뒤죽박죽
domain: sinu.pe.kr
url: https://sinu.pe.kr
baseurl: "/blog"
# twitter_username: 
github_username: sinusinu
repository: sinusinu/blog

author:
  name: "sinu"
  avatar: "/assets/images/profile.jpg"
  bio: 우울한 코딩쟁이
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-brands fa-instagram"
      url: "https://www.instagram.com/just4sinu/"
    - label: "Bluesky"
      icon: "fab fa-fw fa-brands fa-bluesky"
      url: "https://bsky.app/profile/sinu.pe.kr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sinusinu"

minimal_mistakes_skin: "default"
minimal_mistakes_skin_dark: "dark"
locale: "ko-KR"
date_format: "%Y/%m/%d"
search: true
timezone: Asia/Seoul
words_per_minute: 150

comments:
  provider: "giscus"
  giscus:
    repo_id: R_kgDOK6xloQ
    category_name: Comments
    category_id: DIC_kwDOK6xloc4Cb0BW
    discussion_term: pathname
    reactions_enabled: 1
    theme: preferred_color_scheme
    lang: ko
    loading: lazy

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # classes: wide
      show_date: true
      author_profile: true
      comments: true
      read_time: true
      permalink: /posts/:title/
      sidebar:
        - nav: "category-sidebar"
  # category archives
  - scope:
      path: ""
      type: category
    values:
      comments: false
      author_profile: true
      sidebar:
        - nav: "category-sidebar"

atom_feed:
  hide: true

footer:
  links:
    - label: "피드"
      icon: "fas fa-rss-square"
      url: "/blog/feed.xml"
    - label: "CC BY-NC-SA 4.0"
      icon: "fab fa-creative-commons"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ko"

category_archive:
  type: jekyll-archives
  path: /categories/

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive-taxonomy
  permalinks:
    category: /categories/:name/

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
